version: "3.3"
services:
  web:
    environment:
      # This protects your api, make sure it's strong and unique. Consider a password manager generator
      SHARED_SECRET: asdf # Add your own unique strong secret here.
